### PR TITLE
Feat: add iso key

### PR DESCRIPTION
**Pull request by ewolfe**
I found this useful for the scenario where I wanted to highlight the current date and also an arbitrary "selected" date. For example:

image

Having the iso 8601 date makes this a lot easier to do :)

PS: I haven't update the test suite yet (I wanted to get your feedback first before spending the time on the tests).

### CODE REVIEW

**Comment by dance2die** [comment]
Thanks @ewolfe I will check it out tonight after work 😀

**Comment by dance2die** [comment]
@ewolfe Would you also update test cases to match the ISO feature?

You can run the test using `npm test` (I installed `rollup` in the latest that's the reason for lock file change in #18 )

image

**Comment by ewolfe** [comment]
Just pushed a commit that updates the tests.

I also noticed the following error about mixing yarn.lock and package-lock.json:

```console
➜  calendar-dates git:(feat/add-iso-key) yarn
yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.80s.
```

**Comment by dance2die** [comment]
Thank you for the update there @ewolfe. I've merged it right now.

I will update the code again & republish after removing `package-lock.json` which I accidental created ever since I started using `yarn` less.. 😅

**Pull request merged**
