### PR TITLE
Convert async API to a synchronous one

### PR DESCRIPTION
**Pull request by ewolfe**
I ran into the "issue" of this library being async while running jest snapshot testing.

This pull request refactors the API to be synchronous. It also updates all of the documentation, changelog, etc.

### CODE REVIEW

**Comment by ewolfe** [comment]
@dance2die any thoughts on this?

**Comment by dance2die** [comment]
Wow. I am sorry I've not checked this PR (buried in deluge of emails).

May I ask what the issue was with the test?

**Comment by dance2die** [comment]
You can test async code by marking the [callback with async](https://jest-bot.github.io/jest/docs/asynchronous.html#async-await).
Not sure why your snapshot testing would not return data.

I'd like to keep the API async 
and converting the API to be synchronous due to limitation of possible Jest seems backwards to me.

**Comment by ewolfe** [comment]
I can probably get my snapshot testing working. I'm running snapshots via storyshots and they have a guide [here](https://github.com/storybooks/storybook/tree/next/addons/storyshots/storyshots-core#storyshots-for-async-rendered-components). I'm probably just going to use my "sync" fork though since it makes things a little more straight forward.

Maybe I'm missing something though. Does keeping calendar-dates async have any benefits over a synchronous approach?

**Comment by dance2die** [comment]
Synchronous will block the UI while async methods won't.

So if one has to show many months, sync methods will make the site look unresponsive.

**Pull request closed without merging**
